language: rust
sudo: false
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
services:
  - redis-server
script:
  - cargo test
  - cargo doc --no-deps
after_success:
  - bash scripts/travis-doc-upload.sh
notifications:
  irc:
    channels:
      - "chat.freenode.net#coredump"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
